---
name: Azure DDNS
version: 0.0.1
slug: azure_ddns
url: https://github.com/MichallPPP/hassio-addons/tree/master/azure_ddns
description: Dynamic DNS using Microsoft Azure DNS
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
startup: services
boot: auto
options:
  AZURE_TENANT_ID:
  AZURE_SUBSCRIPTION_ID:
  resource_group_name: example
  dns_zone_name: example.net
  record_set_name: "@"
  ttl: 300
  AZURE_USERNAME:
  AZURE_PASSWORD:
schema:
  AZURE_TENANT_ID: str
  AZURE_SUBSCRIPTION_ID: str
  resource_group_name: str
  dns_zone_name: str
  record_set_name: str
  ttl: int
  AZURE_USERNAME: str
  AZURE_PASSWORD: str
